[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/cmt/*"
  to = "/cmt/:splat"
  status = 200

# Handle base path routing
[[redirects]]
  from = "/*"
  to = "/cmt/:splat"
  status = 301

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"